act([
"Kubachi YUT",
"Guest house",
"Reservation",
"Name",
"Email",
"Phone",
"No. of adults",
"Date of arrival",
"Message",
"Submit",
"Rooms",
"Landscapes",
"Food and Drinks",
"Feedbacks about us",
"Give feedback to us",
"Thank you for the feedback",
"Edit",
"Thank you for choosing us!",
"We will call you back soon!",
"No. of childs", 
"Date of departure"
]);
